Repository jiro4989/textimg, pull requests merged in 2021-03, with the labels that each got.

#113 chore: :memo: foreground, backgroundオプションの説明を修正
  internal/global/version.go
  root.go
Labels: chore

#115 各OSでのデフォルトフォントファイルを指定
  docker-compose.yml
  go.mod
  go.sum
  ioimage/face.go
  ioimage/face_test.go
  main_test.go
  root.go
  root_test.go
  testdata/in/illegal_font.otc
  testdata/in/illegal_font.ttc
  testdata/in/illegal_font.txt
Labels: feature

#118 ⬆️ v3へのアップグレード
  README.md
  README_ja.md
  go.mod
  internal/global/version.go
  ioimage/draw.go
  ioimage/face.go
  ioimage/image.go
  log/log.go
  root.go
  root_test.go
Labels: feature

#121 🐛 絵文字の幅がずれるので go-runewidth のバージョンを v0.0.6 に下げた #120
  go.mod
  go.sum
  internal/global/version.go
Labels: bug
